global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'notes-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notes-service:8090']    # замените порт на INTERNAL порт контейнера (SERVICE_PORT внутри образа)

  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak-notes:9000']  # Keycloak контейнер в том же compose

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
