input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Добавим поле service, если его нет
  if ![service] {
    mutate { add_field => { "service" => "my-spring-app" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch-notes:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
